Repository fipguide/fipguide.github.io, pull requests merged in 2025-07, with the labels that each got.

#217 fix: add london international
  content/operator/eurostar/index.de.md
  content/operator/eurostar/index.en.md
Labels: content, operator::eurostar

#215 fix: Scroll to search when using it
  assets/sass/headings.scss
  assets/sass/navigation.scss
  assets/sass/styles.scss
  layouts/partials/search-slot.html
Labels: technical

#203 feat: Add country austria
  content/country/austria/index.de.md
  content/country/austria/index.en.md
Labels: content, operator::oebb, country::austria

#208 refactor: Replace boostrap with custom CSS
  assets/js/highlightHeadline.js
  assets/sass/_variables.scss
  assets/sass/anchorlink.scss
  assets/sass/content.scss
  assets/sass/fonts.scss
  assets/sass/footer.scss
  assets/sass/form.scss
  assets/sass/headings.scss
  assets/sass/main.scss
  assets/sass/navigation.scss
  assets/sass/print.scss
  assets/sass/sidemenu.scss
  assets/sass/startpage.scss
  assets/sass/styles.scss
  assets/sass/teaser.scss
  content/contact/index.de.html
  content/contact/index.en.html
  hugo.yaml
  layouts/404.html
  layouts/_default/baseof.html
  layouts/_default/home.html
  layouts/_default/list.html
  layouts/_default/single.html
  layouts/booking/list.html
  layouts/booking/single.html
  layouts/country/list.html
  layouts/country/single.html
  layouts/news/list.html
  layouts/news/single.html
  layouts/operator/list.html
  layouts/operator/single.html
  layouts/partials/footer.html
  layouts/partials/menu.html
  layouts/partials/shortcut-tile.html
  layouts/partials/sidemenu.html
  layouts/partials/toc.html
  layouts/partials/updateDate.html
  package-lock.json
  package.json
Labels: technical

#218 feat: Add country austria (#203)
  archetypes/operator/index.de.md
  archetypes/operator/index.en.md
  content/booking/eurostar_phone/index.de.md
  content/booking/eurostar_phone/index.en.md
  content/booking/obb_phone/index.de.md
  content/booking/obb_phone/index.en.md
  content/booking/obb_ticket_machine/index.de.md
  content/booking/obb_ticket_machine/index.en.md
  content/booking/obb_ticket_machine/obb_ticket_machine_fip_50.en.webp
  content/booking/obb_ticket_office/index.de.md
  content/booking/obb_ticket_office/index.en.md
  content/booking/obb_website/index.de.md
  content/booking/obb_website/index.en.md
  content/booking/obb_website/obb_reservation.de.webp
  content/booking/obb_website/obb_reservation.en.webp
  content/country/austria/image.webp
  content/country/austria/index.de.md
  content/country/austria/index.en.md
  content/country/belgium/index.de.md
  content/country/belgium/index.en.md
  content/country/denmark/index.de.md
  content/country/denmark/index.en.md
  content/country/netherlands/index.de.md
  content/country/netherlands/index.en.md
  content/country/slovakia/index.de.md
  content/country/slovakia/index.en.md
  content/country/spain/index.de.md
  content/country/spain/index.en.md
  content/news/2/index.de.md
  content/operator/dsb/index.de.md
  content/operator/dsb/index.en.md
  content/operator/eurostar/index.de.md
  content/operator/gysev/index.de.md
  content/operator/gysev/index.en.md
  content/operator/ns/index.de.md
  content/operator/ns/index.en.md
  content/operator/obb/image.webp
  content/operator/obb/index.de.md
  content/operator/obb/index.en.md
  content/operator/renfe/index.de.md
  content/operator/sncb/index.de.md
  content/operator/sncb/index.en.md
  content/operator/zsr/index.de.md
  content/operator/zsr/index.en.md
Labels: content, operator::oebb, country::austria

#230 fix: Scope footnotes to their corresponding booking section
  layouts/partials/booking.html
  layouts/partials/prefix-footnotes.html
Labels: technical

#201 feat: add sbb
  archetypes/booking/index.en.md
  content/booking/db_website_fip_db/index.de.md
  content/booking/db_website_fip_db/index.en.md
  content/booking/db_website_fip_international/index.de.md
  content/booking/db_website_fip_international/index.en.md
  content/booking/obb_phone/index.de.md
  content/booking/obb_phone/index.en.md
  content/booking/renfe_ticket_office/index.de.md
  content/booking/renfe_ticket_office/index.en.md
  content/booking/sbb_ticket_machine/index.de.md
  content/booking/sbb_ticket_machine/index.en.md
  content/booking/sbb_ticket_office/index.de.md
  content/booking/sbb_ticket_office/index.en.md
  content/booking/sbb_website/index.de.md
  content/booking/sbb_website/index.en.md
  content/booking/sbb_website/sbb_reservation.webp
  content/country/austria/index.de.md
  content/country/austria/index.en.md
  content/country/belgium/index.de.md
  content/country/netherlands/index.de.md
  content/country/netherlands/index.en.md
  content/country/slovakia/index.de.md
  content/country/slovakia/index.en.md
  content/country/switzerland/image.webp
  content/country/switzerland/index.de.md
  content/country/switzerland/index.en.md
  content/news/4/index.de.md
  content/operator/dsb/index.de.md
  content/operator/dsb/index.en.md
  content/operator/eurostar/index.de.md
  content/operator/eurostar/index.en.md
  content/operator/ns/index.de.md
  content/operator/ns/index.en.md
  content/operator/obb/index.de.md
  content/operator/obb/index.en.md
  content/operator/renfe/index.de.md
  content/operator/renfe/index.en.md
  content/operator/sbb/image.webp
  content/operator/sbb/index.de.md
  content/operator/sbb/index.en.md
  content/operator/sncb/index.de.md
  content/operator/sncb/index.en.md
  content/operator/zsr/index.de.md
  content/operator/zsr/index.en.md
Labels: content, operator::sbb, country::switzerland

#236 feat: Use human readable format for different image sizes
  layouts/partials/image.html
Labels: technical

#237 fix: Add original image quality to srcset
  layouts/partials/image.html
Labels: technical

#243 feat: Add booking type "machine" for ticket machines
  README.md
  archetypes/booking/index.de.md
  archetypes/booking/index.en.md
  archetypes/booking/index.fr.md
  content/booking/obb-ticket-machine/index.de.md
  content/booking/obb-ticket-machine/index.en.md
  content/booking/obb-ticket-machine/index.fr.md
  content/booking/sbb-ticket-machine/index.de.md
  content/booking/sbb-ticket-machine/index.en.md
  content/booking/sbb-ticket-machine/index.fr.md
  i18n/fr.yaml
  layouts/partials/booking.html
Labels: technical

#246 feat: Add support for dark mode
  assets/js/aside.js
  assets/js/countrySelector.js
  assets/js/darkmode.js
  assets/js/main.js
  assets/sass/_variables.scss
  assets/sass/button.scss
  assets/sass/content.scss
  assets/sass/form.scss
  assets/sass/navigation.scss
  assets/sass/search.scss
  assets/sass/styles.scss
  assets/sass/teaser.scss
  assets/sass/textHighlight.scss
  content/contact/index.de.html
  content/contact/index.en.html
  i18n/de.yaml
  i18n/en.yaml
  i18n/fr.yaml
  layouts/partials/menu.html
  layouts/partials/theme-toggle.html
Labels: technical

#257 refactor: Move `menu` partial into `header` partial
  layouts/partials/header.html
  layouts/partials/menu.html
Labels: technical

#266 fix: Remove background color from operator SVGs
  assets/images/logos/bdz.svg
  assets/images/logos/bls.svg
  assets/images/logos/bsb.svg
  assets/images/logos/cd.svg
  assets/images/logos/cfl.svg
  assets/images/logos/cfr.svg
  assets/images/logos/cie.svg
  assets/images/logos/cp.svg
  assets/images/logos/dsb.svg
  assets/images/logos/eurostar.svg
  assets/images/logos/euskotren.svg
  assets/images/logos/fs.svg
  assets/images/logos/gb.svg
  assets/images/logos/gysev.svg
  assets/images/logos/ht.svg
  assets/images/logos/hzpp.svg
  assets/images/logos/kd.svg
  assets/images/logos/ks.svg
  assets/images/logos/kw.svg
  assets/images/logos/lka.svg
  assets/images/logos/ltg.svg
  assets/images/logos/mav.svg
  assets/images/logos/nir.svg
  assets/images/logos/ns.svg
  assets/images/logos/oebb.svg
  assets/images/logos/pkp.svg
  assets/images/logos/renfe.svg
  assets/images/logos/sbb.svg
  assets/images/logos/sll.svg
  assets/images/logos/sncb.svg
  assets/images/logos/sncf.svg
  assets/images/logos/sp.svg
  assets/images/logos/stl.svg
  assets/images/logos/sz.svg
  assets/images/logos/vr.svg
  assets/images/logos/vy.svg
  assets/images/logos/zpcg.svg
  assets/images/logos/zrs.svg
  assets/images/logos/zrsm.svg
  assets/images/logos/zs.svg
  assets/images/logos/zssk.svg
Labels: technical

#263 fix: Update old references to SVG-icons
  assets/sass/anchorlink.scss
  assets/sass/navigation.scss
  assets/sass/styles.scss
Labels: technical

#262 fix: Improve spacing of mobile navigation menu
  assets/sass/navigation.scss
  layouts/partials/header.html
Labels: technical

#244 feat: Add language switcher
  assets/js/languageSwitcher.js
  assets/js/main.js
  assets/sass/footer.scss
  i18n/de.yaml
  i18n/en.yaml
  i18n/fr.yaml
  layouts/partials/footer.html
  layouts/partials/menu.html
Labels: technical

#258 fix: Use different logo for automatic theme
  assets/js/darkmode.js
  layouts/partials/theme-toggle.html
Labels: technical
