Repository fipguide/fipguide.github.io, pull requests merged in 2025-05, with the labels that each got.

#91 48-texttrenner-before-element-bugfix
  assets/sass/anchorlink.scss
  assets/sass/content.scss
  assets/sass/main.scss
  assets/sass/sidemenu.scss
  assets/sass/stage.scss
  assets/sass/styles.scss
  assets/sass/teaser.scss
  assets/sass/toc.scss
Labels: technical

#92 44-localized-sitetitle
  content/country/_index.de.md
  content/country/_index.en.md
  content/news/_index.de.md
  content/news/_index.en.md
  content/operator/_index.de.md
  content/operator/_index.en.md
  i18n/de.yaml
  i18n/en.yaml
  layouts/_default/list.html
  layouts/country/list.html
  layouts/operator/list.html
Labels: technical

#93 feat: Add new snippet shortcut and note to incomplete pages
  content/country/netherlands/index.de.md
  content/country/netherlands/index.en.md
  content/snippets/wip.de.md
  content/snippets/wip.en.md
  layouts/shortcodes/snippet.html
Labels: content

#63 fix: add eurostar pricing
  content/operator/eurostar/index.de.md
  content/operator/eurostar/index.en.md
Labels: content, operator::eurostar

#100 fix: Reduce margins for anchors
  assets/sass/styles.scss
Labels: technical

#97 feat: Report issues on pages directly from sidemenu
  assets/sass/fonts.scss
  hugo.yaml
  i18n/de.yaml
  i18n/en.yaml
  layouts/_default/_markup/render-link.html
  layouts/partials/icon.html
  layouts/partials/link.html
  layouts/partials/sidemenu.html
Labels: technical

#98 feat: Auto-fetch "last updated" from Git history
  .github/pull_request_template.md
  archetypes/country.de.md
  archetypes/country.en.md
  archetypes/default.md
  archetypes/operator.de.md
  archetypes/operator.en.md
  assets/sass/content.scss
  content/country/belgium/index.de.md
  content/country/belgium/index.en.md
  content/country/netherlands/index.de.md
  content/country/netherlands/index.en.md
  content/country/slovakia/index.de.md
  content/country/slovakia/index.en.md
  content/generalInformation.de.md
  content/generalInformation.en.md
  content/operator/eurostar/index.de.md
  content/operator/eurostar/index.en.md
  content/operator/ns/index.de.md
  content/operator/ns/index.en.md
  content/operator/sncb/index.de.md
  content/operator/sncb/index.en.md
  content/operator/zsr/index.de.md
  content/operator/zsr/index.en.md
  hugo.yaml
  layouts/partials/icon.html
  layouts/partials/updateDate.html
Labels: technical

#118 fix(eurostar): Wrongly places points
  content/operator/sncb/index.en.md
Labels: content, operator::eurostar

#131 fix: HTML rendering in expander
  layouts/shortcodes/expander.html
Labels: technical

#119 feat: Make search usable via keyboard (CTRL + K)
  i18n/de.yaml
  i18n/en.yaml
  layouts/partials/stage.html
Labels: technical

#139 feat: Quick-start for new pages using improved archetypes
  CONTRIBUTING.md
  archetypes/country.de.md
  archetypes/country.en.md
  archetypes/country/index.de.md
  archetypes/country/index.en.md
  archetypes/operator.de.md
  archetypes/operator.en.md
  archetypes/operator/index.de.md
  archetypes/operator/index.en.md
  content/country/belgium/index.en.md
  content/country/denmark/index.en.md
  content/country/netherlands/index.en.md
  content/country/slovakia/index.en.md
  content/operator/ns/index.de.md
  content/operator/ns/index.en.md
Labels: technical

#137 67 add styling for 404 page
  .gitignore
  layouts/404.html
Labels: technical

#61 feat: Add country spain and operator renfe
  content/country/denmark/index.en.md
  content/country/spain/index.de.md
  content/country/spain/index.en.md
  content/operator/renfe/images/ave_ticket.webp
  content/operator/renfe/index.de.md
  content/operator/renfe/index.en.md
Labels: content, country::spain, operator::renfe

#151 feat: Add sitemap to robots.txt
  layouts/robots.txt
Labels: technical

#155 fix: Rendering errors in RSS feed
  layouts/_default/rss.xml
Labels: technical
